// apps/mobile/components/ui/textarea.tsx
import * as React from "react";
import { TextInput, type TextInputProps } from "react-native";
import { cn } from "~/lib/utils";

const Textarea = React.forwardRef<React.ElementRef<typeof TextInput>, TextInputProps>(
    ({ className, multiline = true, numberOfLines = 4, placeholderClassName, ...props }, ref) => {
        return (
            <TextInput
                ref={ref}
                className={cn(
                    "web:flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-base lg:text-sm native:text-lg native:leading-[1.25] text-foreground web:ring-offset-background placeholder:text-muted-foreground web:focus-visible:outline-none web:focus-visible:ring-2 web:focus-visible:ring-ring web:focus-visible:ring-offset-2",
                    props.editable === false && "opacity-50 web:cursor-not-allowed",
                    className
                )}
                placeholderClassName={cn("text-muted-foreground", placeholderClassName)}
                multiline={multiline}
                numberOfLines={numberOfLines}
                textAlignVertical='top'
                {...props}
            />
        );
    }
);

Textarea.displayName = "Textarea";

export { Textarea };

// apps/frontend/src/lib/components/ui/textarea/textarea.svelte
<script lang="ts">
    import type { HTMLTextareaAttributes } from "svelte/elements";
    import type { TextareaEvents } from "./index.js";
    import { cn } from "$lib/utils.js";

    type $$Props = HTMLTextareaAttributes;
    type $$Events = TextareaEvents;

    let className: $$Props["class"] = undefined;
    export let value: $$Props["value"] = undefined;
    export { className as class };

    // Workaround for https://github.com/sveltejs/svelte/issues/9305
    // Fixed in Svelte 5, but not backported to 4.x.
    export let readonly: $$Props["readonly"] = undefined;
</script>

<textarea
    class={cn(
        "border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex min-h-[80px] w-full rounded-md border px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
        className
    )}
    bind:value
    {readonly}
    on:blur
    on:change
    on:click
    on:focus
    on:keydown
    on:keypress
    on:keyup
    on:mouseover
    on:mouseenter
    on:mouseleave
    on:paste
    on:input
    {...$$restProps}
></textarea>
